// client/src/components/Blocs/LatestPost.jsx
import React, { useState } from "react";

const LatestPost = () => {
  const [flag, setFlag] = useState(true);

  return (
    <section className="latest-post-wrapper">
      {flag ? <sup>Soon</sup> : ""}
      <div className="latest-post-navbar">
        <h2>Последние посты</h2>
        <a href="#">Посмотреть все</a>
      </div>
      <div className="latest-posts">
        {/* Post */}
        <div className="latest-post">
          <h2>Новый раздел на сайте</h2>
          <div className="post-subtitle">
            <h4 className="first">12 Мар 2022</h4>
            <h4>Разработка</h4>
          </div>
          <p>
            Новый раздел, где автор будет делиться мыслями, советами и
            интересными фактами. Пока раздел не доступен, т.к находиться в
            разработке.
          </p>
        </div>
        {/* EndPost */}
        {/* Post */}
        <div className="latest-post">
          <h2>Новый раздел на сайте</h2>
          <div className="post-subtitle">
            <h4 className="first">12 Мар 2022</h4>
            <h4>Разработка</h4>
          </div>
          <p>
            Новый раздел, где автор будет делиться мыслями, советами и
            интересными фактами. Пока раздел не доступен, т.к находиться в
            разработке.
          </p>
        </div>
        {/* EndPost */}
      </div>
    </section>
  );
};

export default LatestPost;

// client-reload/src/app/pages/main-page/components/latest-post/latest-post.component.ts
import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'app-latest-post',
  templateUrl: './latest-post.component.html',
  styleUrls: ['./latest-post.component.scss']
})
export class LatestPostComponent implements OnInit {

  constructor() { }

  ngOnInit(): void {
  }

}

<section class="latest-post-wrapper">
  <div class="latest-post-navbar">
    <h2>Последние посты</h2>
    <a href="#">Посмотреть все</a>
  </div>
  <div class="latest-posts">
    <div class="latest-post">
      <h3>Новый раздел на сайте</h3>
      <div class="post-subtitle">
        <h4 class="date">12 Мар 2022</h4>
        <h4>Разработка</h4>
      </div>
      <p>
        Новый раздел, где автор будет делиться мыслями, советами и
        интересными фактами. Пока раздел не доступен, т.к находиться в
        разработке.
      </p>
    </div>
    <div class="latest-post">
      <h3>Новый раздел на сайте</h3>
      <div class="post-subtitle">
        <h4 class="date">12 Мар 2022</h4>
        <h4>Разработка</h4>
      </div>
      <p>
        Новый раздел, где автор будет делиться мыслями, советами и
        интересными фактами. Пока раздел не доступен, т.к находиться в
        разработке.
      </p>
    </div>
  </div>
</section>
