// client-reload/src/app/components/footer/footer.component.ts
import {Component, OnInit} from '@angular/core';
import {FooterDialogService} from "./services/footer-dialog.service";

@Component({
  selector: 'app-footer',
  templateUrl: './footer.component.html',
  styleUrls: ['./footer.component.scss']
})
export class FooterComponent implements OnInit {

  constructor(private readonly footerDialog: FooterDialogService) {
  }

  ngOnInit(): void {
  }

  public show(): void {
    this.footerDialog.openDialog();
  }

}

<footer>
  <div class="footer-wrapper">
    <span class="footer-text">Made by Andrei Solo</span>
    <span class="about-site" (click)="show()">О сайте</span>
    <span class="copy">© Copyright 2022. All rights reserved</span>
  </div>
</footer>

// client/src/components/Blocs/Footer.tsx
import { useState } from 'react';
import Modal from '../UI/modal/Modal.tsx';
import AboutSite from '../AboutSite.tsx';

const Footer = () => {
  const [modal, setModal] = useState(false);

  return (
    <footer>
      <div className='footer-wrapper'>
        <span className='footer-text'>Made by Andrei Solo</span>
        <span className='about-site' onClick={() => setModal(true)}>
          О сайте
        </span>
        <Modal visible={modal} setVisible={setModal}>
          <AboutSite />
        </Modal>
        <span className='copy'>© Copyright 2022. All rights reserved</span>
      </div>
    </footer>
  );
};

export default Footer;
