// client-reload/src/app/pages/main-page/components/news/news.component.ts
import {Component, OnInit} from '@angular/core';

@Component({
  selector: 'app-news',
  templateUrl: './news.component.html',
  styleUrls: ['./news.component.scss']
})
export class NewsComponent implements OnInit {

  public testCount: number[] = [1, 2, 3]

  constructor() {
  }

  ngOnInit(): void {
  }

}

<section class="news-wrapper">
  <h2 class="news-wrapper">Новости</h2>
  <hr>
  <div class="news-list">
    <div class="news-card" *ngFor="let num of testCount">
      <img src="assets/newsImg.png" alt="Новости">
      <div>
        <div class="card-content">
          <h3>Название</h3>
          <h4 class="date">12.22.2021</h4>
          <h4 class="tag">habr</h4>
        </div>
        <p>Amet minim mollit non deserunt ullamco est sit aliqua dolor do amet sint. Velit officia consequat duis enim
          velit mollit. Exercitation veniam consequat sunt nostrud amet.</p>
      </div>
    </div>
  </div>
</section>

// client/src/components/Blocs/News.jsx
import React, { useState, useEffect } from "react";
import Newslist from "../Lists/NewsList.jsx";
import Loader from "../UI/loader/Loader.jsx";
import axios from "axios";

const News = () => {
  const newsData = [
    {
      title: "hello",
      body: "Amet minim mollit non deserunt ullamco est sit aliqua dolor do amet sint. Velit officia consequat duis enim velit mollit. Exercitation veniam consequat sunt nostrud amet.",
      date: "12.22.2334",
      tag: "habr"
    },
    {
      title: "hello",
      body: "Amet minim mollit non deserunt ullamco est sit aliqua dolor do amet sint. Velit officia consequat duis enim velit mollit. Exercitation veniam consequat sunt nostrud amet.",
      date: "12.22.2334",
      tag: "habr"
    },
    {
      title: "hello",
      body: "Amet minim mollit non deserunt ullamco est sit aliqua dolor do amet sint. Velit officia consequat duis enim velit mollit. Exercitation veniam consequat sunt nostrud amet.",
      date: "12.22.2334",
      tag: "habr"
    }
  ];

  const [news, setNews] = useState([]);
  const [loading, setLoading] = useState(false);

  const getTodo = async () => {
    setLoading(true);
    const data = newsData;
    // const data = await axios.get("http://localhost:5000/news/all");
    // const newsData = data.data;
    setNews([...news, ...data]);
    setLoading(false);
  };

  useEffect(() => {
    getTodo();
  }, []);

  return (
    <div className="news-wrapper">
      <div>
        <h2>Новости</h2>
      </div>
      <hr />
      {loading ? (
        <div style={{ textAlign: "center", marginTop: "20px" }}>
          <Loader />
        </div>
      ) : (
        <Newslist news={news} />
      )}
    </div>
  );
};

export default News;
